name: Compile release build

on:
  push:
    branches: [ "main" ]
    paths: [ "src/**" ]

  release:
    types: [ published ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:   
  build_and_upload:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:devel
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential libgtk-4-dev libadwaita-1-dev git curl cmake

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile release build
        run: cargo build --release --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Release build
          path: target/release/honkers-railway-launcher